<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_14_List Comprehensions.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## ðŸŸ© Convert Salaries to EUR (1.14.1)

In [2]:
# Code Needed
salaries_usd = [100000, 120000, 80000, 90000]
salaries_eur = [salary*0.85 for salary in salaries_usd]
salaries_eur

[85000.0, 102000.0, 68000.0, 76500.0]

---

## ðŸŸ¨ Create List of Data Jobs (1.14.2)

In [11]:
# Code Needed
job_experience = {'Data Scientist': 3, 'Data Analyst': 1, 'Machine Learning Specialist': 4, 'Data Engineer': 2}
job_titles = [job for job in job_experience if job_experience[job] > 2]
job_titles

['Data Scientist', 'Machine Learning Specialist']

---

## ðŸŸ¥ Extract High Salary Jobs (1.14.3)

In [18]:
# Code Needed
job_salary_dicts = [
    {'job_title': 'Data Scientist', 'salary': 100000},
    {'job_title': 'Data Analyst', 'salary': 120000},
    {'job_title': 'Data Engineer', 'salary': 80000},
    {'job_title': 'Machine Learning Engineer', 'salary': 90000}
]
high_salary_jobs = [job['job_title'] for job in job_salary_dicts if job['salary'] > 90000]
high_salary_jobs

['Data Scientist', 'Data Analyst']

---