<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_16_Functions.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## ðŸŸ© Job Title Contains (1.16.1)

In [2]:
# Code Needed
job_title = 'Data Scientist'
keyword = 'Data'
def job_title_contains(job_title, keyword):
  if keyword in job_title:
    return True
  else:
    return False

job_title_contains(job_title, keyword)

True

---

## ðŸŸ© Average Salary (1.16.2)

In [3]:
# Code Needed
salaries = [95000, 120000, 105000, 90000, 130000]
def average_salary(salaries):
  average = sum(salaries) / len(salaries)
  return average

average_salary(salaries)

108000.0

---

## ðŸŸ¨ Salary Statistics (1.16.3)

In [5]:
# Code Needed
salaries = [95000, 120000, 105000, 90000, 130000]
def salary_stats(salaries):
  salary_statisitics = {}
  average = sum(salaries) / len(salaries)
  salary_statisitics['min'] = min(salaries)
  salary_statisitics['max'] = max(salaries)
  salary_statisitics['average'] = average

  return salary_statisitics

salary_stats(salaries)

{'min': 90000, 'max': 130000, 'average': 108000.0}

---

## ðŸŸ¥ Job Posting Summary (1.16.4)

In [34]:
# Code Needed
job_postings = [
    {'title': 'Data Scientist', 'location': 'New York', 'salary': 95000},
    {'title': 'Data Analyst', 'location': 'San Francisco', 'salary': 85000},
    {'title': 'Machine Learning Engineer', 'location': 'New York', 'salary': 115000}
]
def job_posting_summary(job_postings):
    total_postings = len(job_postings)
    total_salary = sum(posting['salary'] for posting in job_postings)
    average_salary = total_salary / total_postings
    unique_locations = list(set(posting['location'] for posting in job_postings))
    return {
        'total_postings': total_postings,
        'average_salary': average_salary,
        'unique_locations': unique_locations
    }
job_posting_summary(job_postings)

{'total_postings': 3,
 'average_salary': 98333.33333333333,
 'unique_locations': ['New York', 'San Francisco']}

NameError: name 'func' is not defined

---