<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_21_Classes.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## ðŸŸ© Create JobPosting Class (1.21.1)

In [2]:
# Create the JobPostings class in this code cell
class JobPosting:
  def __init__(self, title, company, location):
    self.title = title
    self.company = company
    self.location = location

In [9]:
# Code Needed
job = JobPosting('Data Scientist', 'Tech Innovations', 'New York')
print(job.title)
print(job.company)
job.location

Data Scientist
Tech Innovations

'New York'

---

## ðŸŸ¨ Convert to Dictionary (1.21.2)

In [10]:
# Create the JobPostings class in this code cell
class JobPosting:
  def __init__(self, title, company, location, salary):
    self.title = title
    self.company = company
    self.location = location
    self.salary = salary
  def to_dict(self):
    return {'title': self.title, 'company': self.company, 'location': self.location, 'salary': self.salary}

In [11]:
# Code Needed
job = JobPosting('Data Scientist', 'Tech Innovations', 'New York', 120000)
job.to_dict()

{'title': 'Data Scientist',
 'company': 'Tech Innovations',
 'location': 'New York',
 'salary': 120000}

---

## ðŸŸ¥ Compare Job Salaries (1.21.3)

In [16]:
# Create the JobPostings class in this code cell
class JobPosting:
  def __init__(self, title, company, location, salary):
    self.title = title
    self.company = company
    self.location = location
    self.salary = salary
  def to_dict(self):
    return {'title': self.title, 'company': self.company, 'location': self.location, 'salary': self.salary}
  def compare_salary(self, other):
    if self.salary > other.salary:
      print(f'{self.title} has a higher salary than {other.title}')
    else:
      print(f'{other.title} has a higher salary than {self.title}')

In [17]:
# Code Needed
job1 = JobPosting('Data Scientist', 'Tech Innovations', 'New York', 120000)
job2 = JobPosting('Data Analyst', 'Data Driven Co', 'San Francisco', 100000)
job1.compare_salary(job2)

Data Scientist has a higher salary than Data Analyst

---